using Litos.Agent.Messages;

namespace Litos.Agent.Session;

public sealed record CompactionSettings(
    bool Enabled = true,
    int ContextWindowTokens = 200_000,
    int ReserveTokens = 16_000,
    int KeepRecentTokens = 20_000,
    int TriggerAtTokens = 184_000)
{
    /// <summary>
    /// Fraction of the model's context window above which compaction fires, when that bound is
    /// the binding one (see ForContextWindow). Keeps the trigger *proportional* — a fixed reserve
    /// alone makes the effective trigger percentage drift upward as windows grow (16K reserve is
    /// 8% of a 200K window but 1.6% of a 1M one).
    /// </summary>
    public const double TriggerFractionOfWindow = 0.65;

    /// <summary>
    /// Absolute ceiling on the trigger, regardless of how large the model's window is. A fraction
    /// alone still scales badly at the top end (0.65 of a 10M window is 6.5M); this is what makes
    /// very large windows land somewhere useful. 250K is the centre of the empirically-measured
    /// optimum band (~220-240K from cost-per-unit-work measurements, usable range ~120-450K):
    /// below ~200K the post-compaction loss of working state starts costing more re-derivation
    /// than it saves, and above ~600K the extra context buys no measurable benefit.
    /// </summary>
    public const int MaxTriggerTokens = 250_000;

    /// <summary>
    /// Fraction of the window kept verbatim (unsummarized) after a cut, once it exceeds the flat
    /// KeepRecentTokens floor. Large windows are exactly where a fixed 20K tail is most lossy, and
    /// tightening the trigger (above) means compaction fires more often — so how much survives
    /// each cut compounds. Agent-compression research finds recency is the single most important
    /// thing to preserve: summarizing recent turns causes execution-state mislocalization (the
    /// agent loses track of where it is), terminal-recognition loss (it keeps working instead of
    /// stopping) and regressive exploration (it re-runs tool calls to rebuild state it just had),
    /// measurable from the very first post-compaction step. A wider verbatim tail is the mitigation
    /// for the extra compaction cycles a tighter trigger introduces, not an independent nicety.
    /// </summary>
    public const double KeepRecentFractionOfWindow = 0.075;

    /// <summary>
    /// Context windows at or below this size keep the pre-existing capacity-only trigger (75% of
    /// the window, via the window/4 ReserveTokens cap) instead of the proportional bound. Small
    /// local models are where over-eager compaction is most damaging — there is little history to
    /// spare, and the replacement summary is generated by that same small model — so the fix for
    /// large-window drift is deliberately not applied to them. 64K is the top of the range local
    /// models are typically served at (see ModelContextWindows.LocalFallbackContextLength, 32K),
    /// and comfortably below the smallest hosted window this table knows about (128K).
    /// </summary>
    public const int SmallWindowThresholdTokens = 64_000;

    /// <summary>
    /// Rescopes this settings record to a specific turn's actual (or best-known-fallback) model
    /// context window, rather than the app-wide default this record is otherwise DI-registered
    /// with (see LitosHostBuilder — one CompactionSettings singleton, historically shared
    /// identically by every provider/model). Without this, a small-context local model's turns
    /// were measured against the 200K default: the trigger stayed unreachable until ~184K
    /// estimated tokens regardless of the real model's window, so compaction effectively never
    /// fired for local sessions — by the time it would have, the real server had already silently
    /// truncated/lost older context.
    ///
    /// TriggerAtTokens is the minimum of three bounds, so one rule covers 8K local models and 1M
    /// hosted ones without special-casing:
    ///   - ContextWindowTokens - ReserveTokens — the hard guard: never ask for more than the
    ///     window holds. This alone governs at or below SmallWindowThresholdTokens, where it
    ///     works out to 75% and preserves the behavior small local models already had.
    ///   - ContextWindowTokens * TriggerFractionOfWindow (binding from there to ~385K) — stops the
    ///     drift that made the effective trigger climb toward 100% as windows grew.
    ///   - MaxTriggerTokens (binding above ~385K) — where 1M-class models land, at 250K/25%.
    /// Before this, only the first bound existed, so the trigger *was* that drift.
    /// The effective trigger was 92% of a 200K window and 98.4% of a 1M one (984K): a turn
    /// spanning many tool-calling rounds re-sent a
    /// near-full context on *every* round (AgentLoop re-checks per round, not per turn), which is
    /// where the cost actually accumulates. Note when tuning: a *too*-low trigger is not free
    /// either — each firing costs a summarization call over everything before the cut, and
    /// compaction overhead grows sharply as the threshold drops.
    ///
    /// ReserveTokens/KeepRecentTokens are still capped to a quarter of the window (not scaled
    /// proportionally to the 200K defaults) so a small window leaves both a nonzero trigger and
    /// cuttable history — reusing the 16K/20K defaults as-is against e.g. an 8K window would make
    /// the trigger negative (compact on every turn) and KeepRecentTokens exceed the whole window
    /// (nothing ever old enough to cut). KeepRecentTokens additionally scales *up* on large
    /// windows (see KeepRecentFractionOfWindow) rather than staying pinned at the 20K default.
    /// </summary>
    public CompactionSettings ForContextWindow(int contextWindowTokens)
    {
        var reserve = Math.Min(ReserveTokens, contextWindowTokens / 4);
        var keepRecent = Math.Min(
            contextWindowTokens / 4,
            Math.Max(KeepRecentTokens, (int)(contextWindowTokens * KeepRecentFractionOfWindow)));

        // Capacity (window - reserve) is never the tighter bound at any window size — the
        // window/4 reserve cap makes it 75% of a small window, and it only climbs from there (92%
        // at 200K, 98.4% at 1M). So a plain Min would apply the 0.65 fraction everywhere, which
        // would make small local models compact *more* eagerly than before this change. That is
        // the opposite of the intent and exactly where over-eager compaction hurts most: a small
        // local model has little history to spare, and the summary replacing it is produced by
        // that same weak model (see ModelContextWindows.LocalFallbackContextLength). Hence the
        // explicit size split rather than a pure lattice of bounds — at or below
        // SmallWindowThresholdTokens the capacity bound alone governs, preserving today's 75%.
        var capacityBound = contextWindowTokens - reserve;
        if (contextWindowTokens <= SmallWindowThresholdTokens)
        {
            return this with
            {
                ContextWindowTokens = contextWindowTokens,
                ReserveTokens = reserve,
                KeepRecentTokens = keepRecent,
                TriggerAtTokens = capacityBound,
            };
        }

        var proportionalBound = Math.Min((int)(contextWindowTokens * TriggerFractionOfWindow), MaxTriggerTokens);

        return this with
        {
            ContextWindowTokens = contextWindowTokens,
            ReserveTokens = reserve,
            KeepRecentTokens = keepRecent,
            TriggerAtTokens = Math.Min(capacityBound, proportionalBound),
        };
    }
}

public sealed record CutPoint(int Index, bool IsSplitTurn, int TurnStartIndex);

/// <summary>
/// Pure functions for deciding whether/where to compact — no I/O, no LLM calls (that
/// part needs a provider and lives in Compactor). Mirrors pi's compaction.ts: never
/// cut between a tool_use message and its tool_result, prefer cutting at user/assistant
/// turn boundaries, and only fire once the *real* usage from the last assistant
/// response exceeds TriggerAtTokens (see CompactionSettings.ForContextWindow).
/// </summary>
public static class CompactionPlanner
{
    private const int EstimatedImageChars = 4800;

    /// <summary>
    /// True if cutting a transcript immediately before this message is safe — i.e. it isn't
    /// a tool result, which must stay glued to the tool_use message that produced it. Shared
    /// by FindCutPoint below and by ITranscriptStore.BranchAsync, which must not truncate a
    /// session mid-tool-call either (a dangling tool_use with no result is rejected by most
    /// providers on the next request).
    /// </summary>
    public static bool IsValidCutPoint(ChatMessage message) =>
        message.Content.OfType<ToolResultBlock>().Any() is false;

    public static bool ShouldCompact(Transcript transcript, CompactionSettings settings)
    {
        if (!settings.Enabled)
            return false;

        var estimatedTokens = EstimatedTokensUsed(transcript);
        if (estimatedTokens is null)
            return false;

        return estimatedTokens > settings.TriggerAtTokens;
    }

    /// <summary>
    /// Real usage from the last assistant response plus a char/4 estimate of trailing messages
    /// sent since — the same figure a context-usage indicator needs, not just ShouldCompact.
    /// Null when no real usage has ever been recorded (nothing to estimate from).
    /// </summary>
    public static int? EstimatedTokensUsed(Transcript transcript)
    {
        var lastUsage = transcript.LastUsage;
        if (lastUsage is null)
            return null;

        var trailingChars = transcript.Messages
            .Skip(transcript.Messages.Count - transcript.MessagesSinceLastUsage)
            .Sum(EstimateChars);
        // TotalInputTokens, not InputTokens: with prompt caching active a provider reports
        // input_tokens as only the post-cache-breakpoint remainder, so the cached prefix — which
        // still occupies the context window in full — would otherwise be invisible here and
        // compaction would never fire (the estimate would sit near zero no matter how long the
        // session ran). Cost and occupancy diverge once caching is on; this is the occupancy path.
        return lastUsage.TotalInputTokens + lastUsage.OutputTokens + trailingChars / 4;
    }

    /// <summary>
    /// Walks backwards accumulating estimated tokens until keepRecentTokens is reached,
    /// then snaps forward to the nearest valid cut point (a user or assistant message —
    /// never a tool result, which must stay glued to the tool_use that produced it).
    /// </summary>
    public static CutPoint? FindCutPoint(IReadOnlyList<ChatMessage> messages, int keepRecentTokens)
    {
        var validCutPoints = new List<int>();
        for (var i = 0; i < messages.Count; i++)
        {
            if (IsValidCutPoint(messages[i]))
                validCutPoints.Add(i);
        }

        if (validCutPoints.Count == 0)
            return null;

        var accumulated = 0;
        var cutIndex = validCutPoints[0];
        for (var i = messages.Count - 1; i >= 0; i--)
        {
            accumulated += EstimateChars(messages[i]) / 4;
            if (accumulated < keepRecentTokens)
                continue;

            cutIndex = validCutPoints.FirstOrDefault(c => c >= i, validCutPoints[^1]);
            break;
        }

        if (cutIndex == 0)
            return null; // nothing old enough to cut

        var isUserTurnStart = messages[cutIndex].Role == Role.User && messages[cutIndex].Content.OfType<ToolResultBlock>().Any() is false;
        var turnStartIndex = isUserTurnStart ? cutIndex : FindTurnStart(messages, cutIndex);

        return new CutPoint(cutIndex, IsSplitTurn: !isUserTurnStart, turnStartIndex);
    }

    /// <summary>
    /// Walks a caller-requested "keep the first N transcript entries" index backwards past any
    /// assistant message whose ToolUseBlock call(s) wouldn't have a matching ToolResultBlock kept
    /// alongside it — an unpaired tool_use is rejected by most providers on the next request. Used
    /// by ITranscriptStore.BranchAsync (JsonlTranscriptStore and FakeTranscriptStore both call
    /// this rather than duplicating the walk) so branching a session can never truncate
    /// mid-tool-call. Operates on TranscriptEntry rather than ChatMessage because the entry index
    /// BranchAsync takes counts every JSONL line, including the non-message "session" header entry
    /// — a requested index that already lands after a completed tool round (or isn't one at all)
    /// is returned unchanged.
    /// </summary>
    public static int SnapToSafeBranchPoint(IReadOnlyList<TranscriptEntry> entries, int uptoEntryIndex)
    {
        var upto = Math.Clamp(uptoEntryIndex, 0, entries.Count);
        while (upto > 0)
        {
            // Every ToolUseBlock call id anywhere among the kept entries — not just the last
            // one — needs its ToolResultBlock kept too: a parallel tool-call round can leave an
            // earlier call's result stranded even when the entry landing exactly at the cut
            // isn't itself a tool_use.
            var kept = entries.Take(upto).ToList();
            var callIds = kept.SelectMany(e => e.Message?.Content.OfType<ToolUseBlock>() ?? []).Select(t => t.CallId);
            var resultCallIds = kept.SelectMany(e => e.Message?.Content.OfType<ToolResultBlock>() ?? []).Select(r => r.CallId).ToHashSet();

            if (callIds.All(resultCallIds.Contains))
                return upto;

            upto--;
        }

        return upto;
    }

    private static int FindTurnStart(IReadOnlyList<ChatMessage> messages, int fromIndex)
    {
        for (var i = fromIndex; i >= 0; i--)
            if (messages[i].Role == Role.User && messages[i].Content.OfType<ToolResultBlock>().Any() is false)
                return i;
        return 0;
    }

    /// <summary>Internal (not private) so ContextBreakdown can reuse the same per-block-type estimate rather than duplicating it.</summary>
    internal static int EstimateChars(ChatMessage message) =>
        message.Content.Sum(block => block switch
        {
            TextBlock t => t.Text.Length,
            ToolUseBlock u => u.ToolName.Length + u.Arguments.GetRawText().Length,
            ToolResultBlock r => r.Text.Length,
            CompactionSummaryBlock c => c.Summary.Length,
            ImageBlock => EstimatedImageChars,
            _ => 0,
        });
}
