# Packages src/Litos.VsCode as a platform-specific .vsix.
#
# vsce's --target flag only tags the .vsix's platform metadata (and filters native node_modules) —
# it does NOT exclude other RIDs' folders under src/Litos.VsCode/bin/, so every targeted platform's
# .vsix would otherwise silently balloon to include all bundled host binaries (see
# ReadMe_VsCodeExtension.md §10.2). This script layers a per-target ignore file on top of the base
# .vscodeignore, excluding every bin/<rid>/ folder except the one the target needs, then packages.
#
# Usage: pwsh deploy/package-vscode-extension.ps1 -Target win32-x64 -Rid win-x64 [-Version 1.0.0]

param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("win32-x64", "win32-arm64", "linux-x64", "linux-arm64", "darwin-x64", "darwin-arm64")]
    [string]$Target,

    [Parameter(Mandatory = $true)]
    [ValidateSet("win-x64", "win-arm64", "linux-x64", "linux-arm64", "osx-x64", "osx-arm64")]
    [string]$Rid,

    [string]$Version
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
$extDir = Join-Path $repoRoot "src/Litos.VsCode"
$allRids = @("win-x64", "win-arm64", "linux-x64", "linux-arm64", "osx-x64", "osx-arm64")

$baseIgnore = Get-Content (Join-Path $extDir ".vscodeignore") -Raw
$otherRidLines = ($allRids | Where-Object { $_ -ne $Rid } | ForEach-Object { "bin/$_/**" }) -join "`n"
$generatedIgnore = Join-Path $extDir ".vscodeignore.$Rid.generated"
Set-Content -Path $generatedIgnore -Value ($baseIgnore + "`n# Other-RID exclusion for this target, generated by package-vscode-extension.ps1`n" + $otherRidLines) -Encoding UTF8

try {
    Push-Location $extDir
    $vsceArgs = @("vsce", "package", "--target", $Target, "--ignoreFile", ".vscodeignore.$Rid.generated")
    if ($Version) { $vsceArgs += $Version }
    & npx @vsceArgs
    if ($LASTEXITCODE -ne 0) {
        throw "vsce package failed with exit code $LASTEXITCODE"
    }
}
finally {
    Pop-Location
    Remove-Item $generatedIgnore -ErrorAction SilentlyContinue
}
