using System.Text;
using System.Text.Json;
using Litos.Agent.Tools;

namespace Litos.Gui;

/// <summary>
/// Schema-only ITool for the reserved run_kernel_code name (ReadMe_PTCPersistentKernel.md §8.2) —
/// registered only when the session's kernel toggle is ON (ToolRegistryFactory.Create in
/// MainWindow), never in the shared LitosHostBuilder, since kernel mode is Litos.Gui-scoped (§2).
/// InvokeAsync is unreachable in practice: AgentLoop intercepts ReservedToolNames.KernelCode by
/// name before ToolRegistry.Resolve is ever reached (AgentLoop.InvokeKernelSafelyAsync) — this
/// body exists purely as a canary a test can assert never fires.
/// </summary>
public sealed class KernelCodeTool(IReadOnlyList<ToolSchema> bridgedToolSchemas) : ITool
{
    public string Name => ReservedToolNames.KernelCode;

    /// <summary>
    /// Built dynamically from the live bridged-tool list, not hand-written (§8.2) — the model's
    /// entire knowledge of what's callable inside the kernel comes from this one field, since
    /// { code: string } gives it nothing else to go on. Regenerated by ToolRegistryFactory.Create()
    /// every turn (§8.2), so a newly enabled MCP server's tools appear here without a restart, the
    /// same way the OFF-state tool list already picks up new MCP tools per-turn.
    /// </summary>
    public string Description
    {
        get
        {
            var sb = new StringBuilder();
            sb.AppendLine(
                "Run a short C# script against a persistent Roslyn scripting kernel. This is your " +
                "ONLY tool this session — every capability below is reached by calling it from " +
                "inside a script, not as a separate tool call. Variables, imports, and locally " +
                "declared functions persist across calls within this session (they do not reset " +
                "between calls). Prefer collapsing multi-step, result-dependent work (e.g. \"read " +
                "file A, and if it imports X also read file B\") into one script rather than several " +
                "separate run_kernel_code calls.");
            sb.AppendLine();
            sb.AppendLine("Available inside the script:");
            sb.AppendLine("- SCRATCH_DIR (string): an absolute path for your own intermediate file writes, outside the project.");
            sb.AppendLine("- KernelState.List() -> IReadOnlyList<string>: lists every variable/function declared so far, with type/size info.");
            sb.AppendLine("- KernelState.Describe(name) -> string: detail on one variable or function by name.");
            foreach (var schema in bridgedToolSchemas)
                sb.AppendLine($"- {schema.Name}(string argsJson) -> Task<string>: {OneLine(schema.Description)}");
            sb.AppendLine();
            sb.AppendLine(
                "Keep your script's own printed output and return value SHORT — a summary like " +
                "\"loaded 40k rows into df\", not the raw data. Large results are automatically " +
                "truncated with a note; nothing you assign to a variable (instead of returning or " +
                "printing it) is resent to you, so prefer keeping intermediate data in variables. " +
                "Every eval's result also reports what changed in kernel state that round (new/" +
                "changed functions and variables) automatically — you do not need to call " +
                "KernelState.List() just to check what you just declared, only to re-orient on " +
                "everything built earlier in a long session.");
            sb.AppendLine();
            sb.AppendLine("Example: var text = await read_file(\"{\\\"path\\\":\\\"a.txt\\\"}\"); text.Contains(\"import X\")");
            sb.AppendLine();
            sb.AppendLine(
                "read_file's output has line-number prefixes for display (like 'cat -n') — never pass " +
                "it straight into write_file or otherwise persist it verbatim, the prefixes are not " +
                "part of the real file content and will corrupt it. For editing an existing file, " +
                "prefer edit_file (targeted old_text/new_text replacement) over a read -> transform -> " +
                "write_file round trip; if you do need the file's raw, unprefixed bytes, read them " +
                "yourself (e.g. System.IO.File.ReadAllText) rather than reusing read_file's formatted output.");
            sb.AppendLine();
            sb.AppendLine(
                "Avoid nesting a raw string literal (\"\"\"...\"\"\") around text that itself contains " +
                "an interpolated string (e.g. an escaped $\"...\") — the two quoting rules stack and " +
                "commonly fail to compile (CS8997/CS1002). Prefer a plain verbatim string (@\"...\", " +
                "doubling any \"\" inside it) for old_text/new_text snippets and other embedded C#-like " +
                "text; it has no such nesting trap.");

            return sb.ToString();
        }
    }

    public JsonElement ParameterSchema { get; } = JsonSerializer.SerializeToElement(new
    {
        type = "object",
        properties = new { code = new { type = "string", description = "The C# script to run." } },
        required = new[] { "code" },
    });

    public Task<ToolResult> InvokeAsync(JsonElement arguments, CancellationToken ct) =>
        Task.FromResult(ToolResult.Error("internal routing error: run_kernel_code should have been intercepted by AgentLoop before reaching ToolRegistry.Resolve"));

    private static string OneLine(string text) => text.Replace("\r", "").Replace("\n", " ").Trim();
}
